# Generated by Django 4.2.3 on 2023-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('favourite', models.BooleanField()),
                ('web_links', models.JSONField(blank=True, null=True)),
                ('media_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
