# Generated by Django 4.2.3 on 2023-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
