# Generated by Django 4.2.3 on 2023-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0002_alter_datastore_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='media_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='web_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
